[project]
name = "hospital-option-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask==2.3.2",
    "flask-login>=0.6.3",
]
